# .github/workflows/ugat.yml

name: WebGuru
on: push

jobs:
  Chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Step 1 - Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Step 2 - Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Step 3 - Install virtualenv
        run: |
          python -m pip install virtualenv
          virtualenv -p python3 .env
          source .env/bin/activate

      - name: Step 4 - Install dependencies, GoogleChrome and Chromedriver
        run: |
          pip install -r requirements.txt

      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '97.0.4692.71'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Step 5 - Run test suite
        run: |
          pytest -s -v --reportportal


